#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Atom-JavaScript
version:      0.2
version_from: lib/XML/Atom/Feed/JavaScript.pm
installdirs:  site
requires:
    XML::Atom:                     0.041
    DateTime:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
